# Development environment override
services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - ./protobuf:/app/protobuf:ro
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  subtitle-generator:
      build:
          context: ./services/subtitle-generator
          dockerfile: ./Dockerfile
          target: dev
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: subtitle-generator

  subtitle-merger:
      build:
          context: ./services/subtitle-merger
          dockerfile: ./Dockerfile
          target: dev
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: subtitle-merger

  sound-extractor:
      build:
          context: ./services/sound-extractor
          dockerfile: ./Dockerfile
          target: dev
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: sound-extractor
