# Production environment override
services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  subtitle-generator:
      build:
          context: ./services/subtitle-generator
          dockerfile: ./Dockerfile
          target: prod
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: subtitle-generator
