framework:
    messenger:
        transports:
            default:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        default:
                            binding_keys: [default]
        routing:
            'App\Protobuf\MediaPod': default
