parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: 'eu-east-1'
                endpoint: 'http://minio:9000/'
                use_path_style_endpoint: true
                credentials:
                    key: 'nOPjahT8v70hZmliVGBM'
                    secret: 'sJ9RoFoxsZCiHveKO5eOfhyAI5Z6bTPXtcmXE5Wt'
