<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SubtitleGeneratorApi</code>
 */
class SubtitleGeneratorApi extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MediaPod mediaPod = 1;</code>
     */
    protected $mediaPod = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protobuf\MediaPod $mediaPod
     * }
     */
    public function __construct($data = NULL) {
        \Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MediaPod mediaPod = 1;</code>
     * @return \Protobuf\MediaPod|null
     */
    public function getMediaPod()
    {
        return $this->mediaPod;
    }

    public function hasMediaPod()
    {
        return isset($this->mediaPod);
    }

    public function clearMediaPod()
    {
        unset($this->mediaPod);
    }

    /**
     * Generated from protobuf field <code>.MediaPod mediaPod = 1;</code>
     * @param \Protobuf\MediaPod $var
     * @return $this
     */
    public function setMediaPod($var)
    {
        GPBUtil::checkMessage($var, \Protobuf\MediaPod::class);
        $this->mediaPod = $var;

        return $this;
    }

}

