<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media-pod.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Video</code>
 */
class Video extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string mimeType = 2;</code>
     */
    protected $mimeType = '';
    /**
     * Generated from protobuf field <code>double size = 3;</code>
     */
    protected $size = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $mimeType
     *     @type float $size
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MediaPod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mimeType = 2;</code>
     * @return string
     */
    public function getMimeType()
    {
        return $this->mimeType;
    }

    /**
     * Generated from protobuf field <code>string mimeType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMimeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->mimeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double size = 3;</code>
     * @return float
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>double size = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->size = $var;

        return $this;
    }

}

